#!/bin/bash
#
# kasutaja tervitus
# 
# skripti algus
#
# echo "Tere User!#
echo -n "Tere "
echo -n `whoami | cut -c1 | tr [:lower] [:upper]` # lõika esimine täht ja muuda suureks
echo -n `whoami | cut -c2-` # lõika kõik tähed alatest 2-st
echo "!"
#
# skripti lopp
