#!/bin/bash
#
# taisnurke kolnumk
#
#loome muutujat nii, et kasutajad sisestavad vaartused ise
echo -n "sisesta a kulja vaartus:"
read a # sellega tekkib a muutuja, mille sisse on salvestatud kasutaja sisestatud vaartus
echo -n "sisesta b kulje vaartus:"
read b
#arvutused
# c = sqrt(a^2 + b^2)
c=$(echo "scale=2;sqrt($a^2 +$b^2)" | bc) # bc arvutusvalem
echo "c= $c"
