#!/bin/bash
#
# taisnurke kolnumk
#
#loome muutujat nii, et kasutajad sisestavad vaartused ise
echo -n "sisesta a kulja vaartus:"
read a # sellega tekkib a muutuja, mille sisse on salvestatud kasutaja sisestatud vaartus
echo -n "sisesta b kulje vaartus:"
read b
echo -n "sisesta c kulje vaartus "
read c
# arvutused
# p = (a + b +c)/2
p=$(echo "scale=2;($a + $b +$c)/2" | bc)
# s =sqrt (p(p - a)(p - b)(p - c))
s=$(echo "scale=2;sqrt($p * ($p - $a) * ($p - $b) * ($p - $c))" | bc)
echo "pindala = $s"

